name: Terraform Apply
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      varStatus: "SUCCESS"

    outputs:
      status: ${{ steps.early.conclusion }}
    steps:
      - name: Print Environment Variabal and ideally set it
        run: |
          echo "Environment var is ${{ env.varStatus }}"
