name: Terraform Apply
on: workflow_dispatch

env:                         # Workflow level environment variable
  dog: "Bowzer the dog"      # can be used in all workflow jobs and steps

jobs:
  dog_job:
    runs-on: ubuntu-latest
    steps:
      - name: "First Dog Step"
        run: echo "Your Pet is ${{ env.dog }}!"

