    jobs:
      build:
        runs-on: ubuntu-latest
        env:
          MY_JOB_VAR: "Hello from job"
        steps:
          - name: Print job variable
            run: echo "Job variable: ${{ env.MY_JOB_VAR }}"
