name: Terraform Apply
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.set_var.outputs.value }}
    steps:
      - id: set_var
        run: echo "value=hello_from_job1" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Accessing variable from job1: ${{ needs.job1.outputs.my_variable }}"
