name: Terraform Apply
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options: [ "dev", "prod", "all"]
        description: "Environment"
        required: true
env:
  WF_ALL_PLANS_EXIST: "SUCCESS"

jobs:
  apply_to_specific_environment:
    if: ${{ inputs.env != 'all' }}
    environment: ${{ inputs.env }}
    name: apply to specific environment (${{ inputs.env }})
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}} 

      - name: Check if file exists in S3
        id: check_s3_file
        run: |
          if aws s3api head-object --bucket ${{ vars.S3_BUCKET }} --key iam_ga/${{ inputs.env }}.txt; then
            echo "file_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "file_exists=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          AWS_PAGER: "" # Disable pager for non-interactive use

      - name: Conditional step based on file existence
        if: steps.check_s3_file.outputs.file_exists == 'true'
        run: |
          echo "The File "${{ inputs.env }}".txt exists in "${{ inputs.env }}" happy days"
          echo "Running all environments - awsome sauce"
          echo "Running in the environment "${{ inputs.env }}
          ls -lartFh
          pwd

  check_plan_on_all_environments:
    if: ${{ inputs.env == 'all'}}
    strategy:
      matrix:
        env: [ "dev", "prod" ]
    environment: ${{ matrix.env }}
    name: Running on All Environments - now on ${{ matrix.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Check if file exists in S3
        id: check_s3_file
        run: |
          if aws s3api head-object --bucket ${{ vars.S3_BUCKET }} --key iam_ga/${{ matrix.env }}.txt; then
            echo "file_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "file_exists=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          AWS_PAGER: "" # Disable pager for non-interactive use

      - name: Modify Global environment variable if a plan does not exist
        if: steps.check_s3_file.outputs.file_exists != 'true'
        run: |
          echo "WF_ALL_PLANS_EXIST=FAIL" >> $GITHUB_ENV
          echo "Not running on All but on "${{ matrix.env }}
          echo "Bye Bye Baby Exiting All"

  apply_on_all_environments:
    needs: check_plan_on_all_environments
    if: ${{ env.WF_ALL_PLANS_EXIST == 'SUCCESS'}}
    name: apply to this stuff now
    runs-on: ubuntu-latest
    steps:
      - name: run some unix commands
        run: |
          echo "The Global variable WF_ALL_PLANS_EXIST has the value "${{ env.WF_ALL_PLANS_EXIST }}
          echo "Exiting the apply to all environments stage - happy days"

