name: Terraform Apply
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options: [ "dev", "prod", "all"]
        description: "Environment"
        required: true

jobs:
  apply_to_specific_environment:
    if: ${{ inputs.env != 'all' }}
    environment: ${{ inputs.env }}
    name: apply to specific environment (${{ inputs.env }})
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}} 

      - name: Check if file exists in S3
        id: check_s3_file
        run: |
          if aws s3api head-object --bucket ${{ vars.S3_BUCKET }} --key iam_ga/${{ inputs.env }}.txt; then
            echo "file_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "file_exists=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          AWS_PAGER: "" # Disable pager for non-interactive use

      - name: First conditional step based on file existence
        if: steps.check_s3_file.outputs.file_exists == 'true'
        run: |
          echo "First Conditional Step"
          echo "The File ${{ inputs.env }}.txt exists in ${{ inputs.env }} happy days"

      - name: Second conditional step based on file existence
        if: steps.check_s3_file.outputs.file_exists == 'true'
        run: |
          echo "Second Conditional Step"
          echo "The File ${{ inputs.env }}.txt exists in ${{ inputs.env }} happy days"

      - name: Third conditional step based on files NON existence
        id: nonexistance_check
        if: steps.check_s3_file.outputs.file_exists != 'true'
        run: |
          echo "Error searching for the File ${{ inputs.env }}.txt - exiting for the environment ${{ inputs.env }}"
          echo "This runs only if we CANNOT file the file ${{ inputs.env }}.txt"


  apply_on_all_environments:
    if: ${{ inputs.env == 'all' }}
    strategy:
      matrix:
        env: [ "development", "prod" ]
    environment: ${{ matrix.env }}

    name: apply to all environments
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Check if file exists in S3
        id: check_s3_file
        run: |
          if aws s3api head-object --bucket ${{ vars.S3_BUCKET }} --key iam_ga/${{ matrix.env }}.txt; then
            echo "file_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "file_exists=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          AWS_PAGER: "" # Disable pager for non-interactive use

      - name: First conditional step based on file existence
        if: steps.check_s3_file.outputs.file_exists == 'true'
        run: |
          echo "First Conditional Step - based on files existance"
          echo "The File ${{ matrix.env }}.txt exists in the environment ${{ matrix.env }} happy days"

      - name: Second conditional step based on file existence
        if: steps.check_s3_file.outputs.file_exists == 'true'
        run: |
          echo "Second Conditional Step - based on file existance"
          echo "The File ${{ matrix.env }}.txt exists in the environment ${{ matrix.env }} happy days"

      - name: Third conditional step based on files NON existence
        id: nonexistance_check
        if: steps.check_s3_file.outputs.file_exists != 'true'
        run: |
          echo "Error searching for the File ${{ matrix.env }}.txt - exiting for the environment ${{ matrix.env }}"
          echo "This runs only if we CANNOT file the file ${{matrix.env}}.txt"
