    name: My Workflow
    on: [push]

    env:
      MY_GLOBAL_VAR: "Hello from workflow"

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Print global variable
            run: echo "Global variable: ${{ env.MY_GLOBAL_VAR }}"
