name: Terraform Apply
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options: [ "dev", "prod", "all"]
        description: "Environment"
        required: true

jobs:
  apply_to_specific_environment:
    if: ${{ inputs.env }} != "all"
    environment: ${{ inputs.env }}
    name: apply to (${{ inputs.env }})
    runs-on: ubuntu-latest
    steps:
      - name: Run some unix commands to finish off
        run: |
          ls -lartFh
          echo "Bye Bye Baby"

  apply_to_all_environments:
    if: ${{ inputs.env }} == "all"
    environment: ${{ inputs.env }}
    name: apply to (${{ inputs.env }})
    runs-on: ubuntu-latest
    steps:
      - name: Run some unix commands to finish off
        run: |
          echo "Running all environments - awsome sauce"
          echo "Running in the environment "${{ inputs.env }} 
          ls -lartFh
          pwd

