name: Terraform Apply
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      varStatus: "SUCCESS"
    steps:
      - name: Print Environment Variable
        run:  echo "Environment var is ${{ env.varStatus }}"

      - name: Overwrite Environment Variable
        run:  echo "varStatus=FAILURE" >> $GITHUB_ENV

      - name: Print Environment Variable
        run:  echo "Environment var is ${{ env.varStatus }}"
