name: Terraform Apply
on: [push]

env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"
  WF_ALL_PLANS_EXIST: "SUCCESS"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use workflow variable
        run: echo "Accessing workflow variable: ${{ env.MY_WORKFLOW_VARIABLE }}"
